name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    shell: bash -l {0}

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: test
        mamba-version: "*"
        channels: conda-forge

    - name: Conda install dependencies
      run: |
        conda env update --file ci/environment.yml --name test

    - name: Lint check
      run: |
        make clean
        make lint
        make typing

    - name: Test check
      env:
        XYZ_TOKEN: ${{ secrets.XYZ_TOKEN }}
        LS_API_KEY: ${{ secrets.LS_API_KEY }}
      run: |
        pytest -v --durations=10 --cov-report=xml --cov=here_location_services tests

    - name: Upload coverage to Codecov
      if: github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-latest' && matrix.python-version == '3.8'
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        verbose: true

    - name: Build Docs (Only on Linux for saving time)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sh scripts/build_docs.sh

    - name: Install here-location-services
      run: pip install .

    - name: Build the package (Only on Linux for saving time)
      if: matrix.os == 'ubuntu-latest'
      run: |
        python setup.py sdist bdist_wheel
